### ISSUE TITLE
Use LSP support in HHVM 3.23+

### ISSUE THREAD

**Issue by fredemmott** [PranayAgarwal/vscode-hack#15]
in master, `hh_client lsp` gets you a vscode LSP server

if you're on mac, you can get a recent enough build of HHVM/hh_client by following https://github.com/facebook/nuclide/issues/1358#issuecomment-339779359

**Comment by PranayAgarwal** [comment]
🎉 Been waiting for this. BTW is there a good way to know the version of `hh_client` the machine is using? `hh_client --version` isn't too useful for this, and I don't want to break pre-3.23 versions.

**Comment by ljw1004** [comment]
`hh_client --version --json` was introduced in 3.15. Currently as of 3.18 it outputs `"api_version":4`. Once I'm happy that LSP support is good enough to leave beta then I'll bump it up to `"api_version":5` (aiming for v3.23 out on Nov17th). Clients can rely that if `api_version>=5` then they can use LSP.

**Comment by PranayAgarwal** [comment]
Hi @ljw1004, this is for the Hack extension for Visual Studio Code published at https://marketplace.visualstudio.com/items?itemName=pranayagarwal.vscode-hack. I want to selectively switch newer clients to use `hh_client` in LSP mode, while older ones will continue to call the various IDE-related commands and parse the output.

**Comment by PranayAgarwal** [comment]
I just released v0.6.1 of the extension which has optional language server support. It is turned off by default for now, so if you're on HHVM 3.23+ add `"hack.useLanguageServer": true` to your settings and reload the workspace.

Logs go to the "Output" pane -> "Hack Language Server" source in the dropdown filter.

If all goes well, I'll turn it on by default in a future version.

**Comment by fredemmott** [comment]
FYI, Nuclide 0.275's switched over, with an opt-out in settings.

**Comment by PranayAgarwal** [comment]
Awesome, I'll set LSP as default for VS Code as well in the next version.

**Comment by PranayAgarwal** [comment]
This was enabled by default in https://github.com/PranayAgarwal/vscode-hack/commit/a17cf9214a8193f1852c2cdfa12b3708c2693317.
