### ISSUE TITLE
Detect Hack files by content

### ISSUE THREAD

**Issue by fredemmott** [PranayAgarwal/vscode-hack#20]
e.g. vscode is unaware that https://github.com/hhvm/hhast/blob/master/bin/hhast-lint is a Hack file

**Comment by PranayAgarwal** [comment]
Hmm, I'm thinking looking for `#!.*hhvm.*` in the first line will be the easiest fix. Thoughts?

**Comment by PranayAgarwal** [comment]
https://github.com/PranayAgarwal/vscode-hack/commit/fc59bab43ec8d2cf2d12e90ee24d869fbece2a71
