### ISSUE TITLE
Support type coverage via textDocument/typeCoverage method

### ISSUE THREAD

**Issue by fredemmott** [PranayAgarwal/vscode-hack#23]
FB extension to the LSP.

Signatures here: https://github.com/facebook/hhvm/blob/master/hphp/hack/src/utils/lsp.ml#L687

**Comment by fredemmott** [comment]
There's also a super-strict mode that can somehow be enabled with this, though I haven't dug in enough to see how it's activated.

**Comment by PranayAgarwal** [comment]
Ran into some trouble implementing this yesterday, and I think the problem is on the hh_client side (was able to repro on Nuclide as well). Filed https://github.com/facebook/hhvm/issues/8257.
