### ISSUE TITLE
Include error code in messages

### ISSUE THREAD

**Issue by fredemmott** [PranayAgarwal/vscode-hack#9]
Useful for adding HH_IGNORE_ERROR - eg hh_client shows:

```
Too few arguments (Typing[4104])
```

vscode just shows "Too few arguments"

If I know what I'm doing, I can add:

```
/* HH_IGNORE_ERROR[4104]  */
or
/* HH_FIXME[4104] */
```

**Comment by PranayAgarwal** [comment]
Added error code, but `hh_client` doesn't return error category for `--json` formatted responses. Code will be enough for this use case, however.

**Comment by PranayAgarwal** [comment]
Filed for follow-up: https://github.com/facebook/hhvm/issues/7484

**Comment by fredemmott** [comment]
We believe hack is exposing this correctly, and it's up to the editor/extension to expose this (as nuclide and vim-lsp do).  This should be re-opened, but hopefully fixed by me soon (FB: P59796946 T31296958)

**Comment by fredemmott** [comment]
oh, though this task was originally for --json not lsp :)

**Comment by PranayAgarwal** [comment]
Yeah, we can repurpose it

**Comment by fredemmott** [comment]
#25
